/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LinksRouteImport } from './routes/links'
import { Route as DisclosureRouteImport } from './routes/disclosure'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesIndexRouteImport } from './routes/stories/index'
import { Route as RecommendIndexRouteImport } from './routes/recommend/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as StoriesTheAccidentWasntHisFaultRouteImport } from './routes/stories/the-accident-wasnt-his-fault'
import { Route as RecommendPottyTrainingRouteImport } from './routes/recommend/potty-training'
import { Route as BlogWhyPuppyAccidentsArentHisFaultRouteImport } from './routes/blog/why-puppy-accidents-arent-his-fault'
import { Route as BlogHowToReadPuppySignalsRouteImport } from './routes/blog/how-to-read-puppy-signals'
import { Route as BlogFivePottyTrainingMistakesRouteImport } from './routes/blog/five-potty-training-mistakes'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosureRoute = DisclosureRouteImport.update({
  id: '/disclosure',
  path: '/disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendIndexRoute = RecommendIndexRouteImport.update({
  id: '/recommend/',
  path: '/recommend/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesTheAccidentWasntHisFaultRoute =
  StoriesTheAccidentWasntHisFaultRouteImport.update({
    id: '/stories/the-accident-wasnt-his-fault',
    path: '/stories/the-accident-wasnt-his-fault',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecommendPottyTrainingRoute = RecommendPottyTrainingRouteImport.update({
  id: '/recommend/potty-training',
  path: '/recommend/potty-training',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWhyPuppyAccidentsArentHisFaultRoute =
  BlogWhyPuppyAccidentsArentHisFaultRouteImport.update({
    id: '/blog/why-puppy-accidents-arent-his-fault',
    path: '/blog/why-puppy-accidents-arent-his-fault',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHowToReadPuppySignalsRoute =
  BlogHowToReadPuppySignalsRouteImport.update({
    id: '/blog/how-to-read-puppy-signals',
    path: '/blog/how-to-read-puppy-signals',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogFivePottyTrainingMistakesRoute =
  BlogFivePottyTrainingMistakesRouteImport.update({
    id: '/blog/five-potty-training-mistakes',
    path: '/blog/five-potty-training-mistakes',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/characters': typeof CharactersRoute
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/faq': typeof FaqRoute
  '/links': typeof LinksRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/five-potty-training-mistakes': typeof BlogFivePottyTrainingMistakesRoute
  '/blog/how-to-read-puppy-signals': typeof BlogHowToReadPuppySignalsRoute
  '/blog/why-puppy-accidents-arent-his-fault': typeof BlogWhyPuppyAccidentsArentHisFaultRoute
  '/recommend/potty-training': typeof RecommendPottyTrainingRoute
  '/stories/the-accident-wasnt-his-fault': typeof StoriesTheAccidentWasntHisFaultRoute
  '/blog/': typeof BlogIndexRoute
  '/recommend/': typeof RecommendIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/characters': typeof CharactersRoute
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/faq': typeof FaqRoute
  '/links': typeof LinksRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/five-potty-training-mistakes': typeof BlogFivePottyTrainingMistakesRoute
  '/blog/how-to-read-puppy-signals': typeof BlogHowToReadPuppySignalsRoute
  '/blog/why-puppy-accidents-arent-his-fault': typeof BlogWhyPuppyAccidentsArentHisFaultRoute
  '/recommend/potty-training': typeof RecommendPottyTrainingRoute
  '/stories/the-accident-wasnt-his-fault': typeof StoriesTheAccidentWasntHisFaultRoute
  '/blog': typeof BlogIndexRoute
  '/recommend': typeof RecommendIndexRoute
  '/stories': typeof StoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/characters': typeof CharactersRoute
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/faq': typeof FaqRoute
  '/links': typeof LinksRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/five-potty-training-mistakes': typeof BlogFivePottyTrainingMistakesRoute
  '/blog/how-to-read-puppy-signals': typeof BlogHowToReadPuppySignalsRoute
  '/blog/why-puppy-accidents-arent-his-fault': typeof BlogWhyPuppyAccidentsArentHisFaultRoute
  '/recommend/potty-training': typeof RecommendPottyTrainingRoute
  '/stories/the-accident-wasnt-his-fault': typeof StoriesTheAccidentWasntHisFaultRoute
  '/blog/': typeof BlogIndexRoute
  '/recommend/': typeof RecommendIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/characters'
    | '/contact'
    | '/disclosure'
    | '/faq'
    | '/links'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blog/five-potty-training-mistakes'
    | '/blog/how-to-read-puppy-signals'
    | '/blog/why-puppy-accidents-arent-his-fault'
    | '/recommend/potty-training'
    | '/stories/the-accident-wasnt-his-fault'
    | '/blog/'
    | '/recommend/'
    | '/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/characters'
    | '/contact'
    | '/disclosure'
    | '/faq'
    | '/links'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blog/five-potty-training-mistakes'
    | '/blog/how-to-read-puppy-signals'
    | '/blog/why-puppy-accidents-arent-his-fault'
    | '/recommend/potty-training'
    | '/stories/the-accident-wasnt-his-fault'
    | '/blog'
    | '/recommend'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/characters'
    | '/contact'
    | '/disclosure'
    | '/faq'
    | '/links'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blog/five-potty-training-mistakes'
    | '/blog/how-to-read-puppy-signals'
    | '/blog/why-puppy-accidents-arent-his-fault'
    | '/recommend/potty-training'
    | '/stories/the-accident-wasnt-his-fault'
    | '/blog/'
    | '/recommend/'
    | '/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CharactersRoute: typeof CharactersRoute
  ContactRoute: typeof ContactRoute
  DisclosureRoute: typeof DisclosureRoute
  FaqRoute: typeof FaqRoute
  LinksRoute: typeof LinksRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogFivePottyTrainingMistakesRoute: typeof BlogFivePottyTrainingMistakesRoute
  BlogHowToReadPuppySignalsRoute: typeof BlogHowToReadPuppySignalsRoute
  BlogWhyPuppyAccidentsArentHisFaultRoute: typeof BlogWhyPuppyAccidentsArentHisFaultRoute
  RecommendPottyTrainingRoute: typeof RecommendPottyTrainingRoute
  StoriesTheAccidentWasntHisFaultRoute: typeof StoriesTheAccidentWasntHisFaultRoute
  BlogIndexRoute: typeof BlogIndexRoute
  RecommendIndexRoute: typeof RecommendIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosure': {
      id: '/disclosure'
      path: '/disclosure'
      fullPath: '/disclosure'
      preLoaderRoute: typeof DisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommend/': {
      id: '/recommend/'
      path: '/recommend'
      fullPath: '/recommend/'
      preLoaderRoute: typeof RecommendIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/the-accident-wasnt-his-fault': {
      id: '/stories/the-accident-wasnt-his-fault'
      path: '/stories/the-accident-wasnt-his-fault'
      fullPath: '/stories/the-accident-wasnt-his-fault'
      preLoaderRoute: typeof StoriesTheAccidentWasntHisFaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommend/potty-training': {
      id: '/recommend/potty-training'
      path: '/recommend/potty-training'
      fullPath: '/recommend/potty-training'
      preLoaderRoute: typeof RecommendPottyTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/why-puppy-accidents-arent-his-fault': {
      id: '/blog/why-puppy-accidents-arent-his-fault'
      path: '/blog/why-puppy-accidents-arent-his-fault'
      fullPath: '/blog/why-puppy-accidents-arent-his-fault'
      preLoaderRoute: typeof BlogWhyPuppyAccidentsArentHisFaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-read-puppy-signals': {
      id: '/blog/how-to-read-puppy-signals'
      path: '/blog/how-to-read-puppy-signals'
      fullPath: '/blog/how-to-read-puppy-signals'
      preLoaderRoute: typeof BlogHowToReadPuppySignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/five-potty-training-mistakes': {
      id: '/blog/five-potty-training-mistakes'
      path: '/blog/five-potty-training-mistakes'
      fullPath: '/blog/five-potty-training-mistakes'
      preLoaderRoute: typeof BlogFivePottyTrainingMistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CharactersRoute: CharactersRoute,
  ContactRoute: ContactRoute,
  DisclosureRoute: DisclosureRoute,
  FaqRoute: FaqRoute,
  LinksRoute: LinksRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogFivePottyTrainingMistakesRoute: BlogFivePottyTrainingMistakesRoute,
  BlogHowToReadPuppySignalsRoute: BlogHowToReadPuppySignalsRoute,
  BlogWhyPuppyAccidentsArentHisFaultRoute:
    BlogWhyPuppyAccidentsArentHisFaultRoute,
  RecommendPottyTrainingRoute: RecommendPottyTrainingRoute,
  StoriesTheAccidentWasntHisFaultRoute: StoriesTheAccidentWasntHisFaultRoute,
  BlogIndexRoute: BlogIndexRoute,
  RecommendIndexRoute: RecommendIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
